mysite/muffinShop/urls.py
from django.urls import path

from . import views


app_name = 'muffinShop'
urlpatterns = [

    # ex.  /muffinShop/
    path('', views.index,  name='index'),
    #path('', views.IndexView.as_view(), name='index'),

    path('order/', views.order, name='order'),
    #ex./muffinShop/order


    # ex./muffinShop/order/confirm
    path('order/confirm', views.confirm ,name='confirm'),

    # ex./muffinShop/check
    path('check/', views.check, name='check'),

    # ex./muffinShop/check_order
    path('check_order', views.check_order, name='check_order'),
    path('test' ,views.test, name='test')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('muffinShop/', include('muffinShop.urls')),
    path('admin/', admin.site.urls),

]

mysite/muffinShop/models.py
from django.db import models


class Product(models.Model):
    class Category(models.TextChoices):
        MUFFIN = ' Muffin'
        COOKIE = ' Cookie'
        CUPCAKE = ' Cupcake'

    product_id = models.AutoField(primary_key=True )
    product_number = models.PositiveSmallIntegerField()
    category = models.CharField(max_length=10, choices=Category.choices)
    product_name = models.CharField(max_length=50, )
    price = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.product_name + self.category

    def product_full_name(self):
        return f'{self.product_name} +{self.category}'


class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_date = models.DateTimeField(null=True)
    total_price = models.PositiveIntegerField(blank=True, null=True)
    user_name = models.CharField(max_length=10, null=True)
    user_phone = models.CharField(max_length=15, null=True)
    user_address = models.CharField(max_length=50, null=True)

    # payment = models.
    def __str__(self):
        return str(self.order_id)


class OrderItem(models.Model):
    orderItem_id = models.AutoField(primary_key=True)
    order = models.ForeignKey('Order', on_delete=models.CASCADE,)
    product = models.ForeignKey('Product', on_delete=models.CASCADE,)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.order_id)
        #return f"order: {self.order_id}: {self.product_id} x {self.quantity}"
        # def orderId = ~ 오더아이디클래스에서 order_id 중 가장 가장 큰 수+1 해서 orderId에 집어넣고

# each_price = product.price * cart.quantity

# def totalPrice(self): each_price의 합

# 질문 ...진행 순서상 카트에 먼저 담기는데 카트에 먼저 order_id를 부여하면,
# order_id 를 foreign키로 해야하는지...

mysite/muffinShop/forms.py
from datetime import datetime

from django import forms

from . import models
from .models import Product, OrderItem, Order
from django.core.validators import RegexValidator
#
# class InputForm(forms.ModelForm):
#
#     class Meta:
#         model = OrderItem
#         fields = ('quantity',)


class InputForm(forms.Form):
    product_number = forms.IntegerField(min_value=1,max_value=11, initial=1, label="품번")
    quantity = forms.IntegerField(min_value=1,max_value=10, initial=1, required=False, label="수량")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""


class NumberForm(forms.Form):
    number = forms.CharField(max_length=11, label='')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""


class OrderForm(forms.ModelForm):
    order_date = forms.DateField(initial=datetime.now(), label="주문일")
    user_name = forms.CharField(max_length=20, label="성함")
    user_phone = forms.CharField(max_length=20, label="폰번호")
    user_address = forms.CharField(max_length=50, label="주소")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""

    class Meta:
        model = Order
        fields = [
            'order_date', 'user_name', 'user_phone', 'user_address'
        ]

#
# def phone_validator:
#     phone_number_validator= RegexValidator(r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')

mysite/muffinShop/views.py
from datetime import datetime, timedelta
from django.http import HttpResponse
from django.shortcuts import render
from .forms import InputForm, NumberForm, OrderForm
from .models import OrderItem, Order, Product


def index(request):
    if request.method == 'GET':
        products = Product.objects.all()
        form = InputForm()
        print('inputform()')
        context = {
            'products': products,
            'form': form,
        }
        return render(request, 'muffinShop/index.html', context)
    else:
        context = {
            'error_message': '현재 준비중인 상품이 없습니다',
        }
        return render(request, 'muffinShop/index.html', context)


def order(request):
    if request.method == 'POST':
        quantity = request.POST['quantity']
        product_number = request.POST['product_number']
        product = Product.objects.get(product_number=product_number)
        print(quantity)
        print(product_number)
        total_price = int(quantity) * int(product.price)  # 받아온 값은 str,형변환 필요
        order_form = OrderForm()
        context = {
            'quantity': quantity,
            'product': product,
            'order_form': order_form,
            'total_price': total_price
        }
        return render(request, 'muffinShop/order.html', context)
    else:
        products = Product.objects.all()
        form = InputForm()
        context = {
            'products': products,
            'form': form,
            'error_message': '다시 골라주세요',
        }
        return render(request, 'muffinShop/index.html', context)


def confirm(request):
    if request.method == "POST":
        order_form = OrderForm(request.POST)

        if order_form.is_valid():
            quantity = request.POST['quantity']
            product_id = request.POST['product_id']
            product = Product.objects.get(product_id=product_id)
            print(product_id)
            print(quantity)
            order = order_form.save()
            order.total_price = int(product.price) * int(quantity)
            order.order_date = datetime.now().strftime("%Y-%m-%d %H:%M")
            order.save()
            orderitem = OrderItem.objects.create(
                order_id=order.order_id,
                product_id=product_id,
                quantity=quantity,
            )
            orderitem.save()
            context = {
                'order': order,
                'orderitem' : orderitem,
                'product':product,
            }
            return render(request, 'muffinShop/confirm.html', context)
        else:
            products = Product.objects.all()
            form = InputForm()
            context = {
                'products': products,
                'form': form,
                'error_message': '입력양식이 잘못되어 처음으로 돌아옵니다.',
            }
            return render(request, 'muffinShop/index.html', context)
    else:
        products = Product.objects.all()
        form = InputForm()
        context = {
            'products': products,
            'form': form,
            'error_message': '입력양식이 잘못되어 처음으로 돌아옵니다.',
        }
        return render(request, 'muffinShop/index.html', context)



def check(request):
    form = NumberForm()
    return render(request, 'muffinShop/check.html', {'form': form})


def check_order(request):
    form = NumberForm(request.POST)
    if form.is_valid():
        number = form.cleaned_data['number']
        order_info = Order.objects.filter(user_phone=number)
        list = []
        for order in order_info:
            order_id = order.order_id
            orderitem_info = OrderItem.objects.filter(order_id=order_id)
            order_date = order.order_date.strftime("%Y-%m-%d")
            list.append(f"\n{order.user_name}님의 주문내역\n 주문일 {order_date} \n "
                        f"지불비용 {order.total_price}\n"
                        f" 전화번호 {order.user_phone} \n 주소 {order.user_address} \n")
            for item in orderitem_info:
                product = Product.objects.get(product_id=item.product_id)
                product_name = product.product_name
                price = product.price
                qt = item.quantity
                item_price = price * qt
                str = f"{product_name}{product.category}({price}) X {qt} = {item_price}\n"
                list.append(str)

        context = {
            'order_info': order_info,
            'orderitem_info': orderitem_info,
            'list': list,
            'error_message': '입력양식이 잘못되어 처음으로 돌아옵니다.',
        }
        return render(request, 'muffinShop/check_phone.html', context)
    else:
        return render(request, 'muffinShop/check.html', {'form': form})


def test(request):
    return HttpResponse('<h1>hello</h1>')

mysite/muffinShop/templates/muffinShop/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@300&display=swap" rel="stylesheet" />
    <link rel="stylesheet"  href="{% static 'css/muffinShop.css' %}" />
    <link href="{% static 'asset/image/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <title>MuffinShop</title>
    <script defer src="{% static 'js/muffinShop.js'  %}"></script>
  </head>
  <body>
    <header>
      <div id="title">
        <a href="/muffinShop"><img src="{% static 'asset/image/main-logo.png' %}" alt="머핀샵 로고" width="300rem" /></a>
      </div>
      <nav id="main_gnb">
        <ul>
          <li><a href="/muffinShop/check">주문확인</a></li>
        </ul>
      </nav>
    </header>
     <div class="container">
      {% block content %}
      {% endblock %}

    </div>



  </body>
</html>

mysite/muffinShop/templates/muffinShop/check.html
{% extends 'muffinShop/base.html' %} {% block content %}

<div id="input-number">
  <p>주문 시 작성하신 휴대폰 번호를 입력하세요</p>
  <form action="{% url 'muffinShop:check_order'  %}" method="post">
    {% csrf_token %}
      {{form.as_table}}
      <input type="submit" name="input" value="입력" />
  </form>
</div>
{% endblock %}

mysite/muffinShop/templates/muffinShop/check_phone.html
{% extends 'muffinShop/base.html' %}
{% block content %}
{%if order_info%}
    {%if orderitem_info%}
        <div id="check-phone">
        {{list |join:" "|linebreaksbr }}
        </div>
    {% endif %}
{% endif %}
{% endblock %}

mysite/muffinShop/templates/muffinShop/confirm.html
{% extends 'muffinShop/base.html' %}
{% block content %}
{% if order %}
{% csrf_token %}
<div class="confirm">
  <p> {{order.user_name}}님의 주문내역</p>
    <ul>
      <li>주문상품 : {{product.product_name}}{{ product.category}}</li>
      <li>주문수량 : {{orderitem.quantity}}개</li>
      <li>총 가격 : {{order.total_price}}</li>
      <li>주문일자 : {{order.order_date}}</li>
      <li>번호 : {{order.user_phone}}</li>
      <li>주소: {{order.user_address}}</li>
    </ul>

</div>
{% endif %} {% endblock %}

mysite/muffinShop/templates/muffinShop/index.html
{% extends 'muffinShop/base.html' %}
{% block content %}
<section class="order_section">
	<div class="order_products">
	{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
	<br/>
	{% endif %}
	{% if products %}
	{% for product in products %}
	<p class="product" id="product_{{product.product_number}}">{{product.product_number}}. {{product.product_name}}{{product.category}}
		({{product.price}})</p>
	{% endfor %}
 </div>

<div class="main_order">
	<div class="main_order_pic"><img src="https://media.bakingmad.com/app_/responsive/BakingMad/media/content/Recipes/Cupcakes-Muffins/Muffins/Snickerdoodle-muffins/1-Snickerdoodle-Muffins-web.jpg?w=1300" width="300rem" height="300rem" alt="머핀사진"/></div>
	<div class="main_order_choice">
	<form class="post-form" action="{% url 'muffinShop:order'  %}" method="post">
		{% csrf_token %} {{form.as_p}}
		<input type="submit" id="order_aside_submit" value="주문하기"/>
	</form>
		</div>
</div>
</section>
{% endif %}
{% endblock %}

mysite/muffinShop/templates/muffinShop/order.html
{% extends 'muffinShop/base.html' %} {% block content %}

<form method="POST" action="{% url 'muffinShop:confirm'  %}" class="post-form">
	{% csrf_token %}
	<input type="number" name="product_id" value="{{product.product_id}}" hidden/>
	<p>
		<label for="product_name"></label>
		<input type="hidden" name="product_name" value="{{product.product_name}}{{product.category}}" id="product_name"/>
	</p>
	<p><label for="qt"></label> <input type="hidden" name="quantity" value="{{quantity}}" id="qt" readonly/></p>
	<p>
		<label for="price"></label>
		<input
			type="hidden"
			name="total_price"
			value="{{quantity}}*{{product.price}}= {{total_price}}"
			id="price"
			readonly
		/>
	</p>
	<div id="order_detail">
		<div>
			<table id="order_detail_table">
				<tr>
					<th>제품명</th>
					<td>{{product.product_name}}{{product.category}}</td>
				</tr>
				<tr>
					<th>수량</th>
					<td>{{quantity}} 개</td>
				</tr>
				<tr>
					<th>가격</th>
					<td>{{product.price}}원 * {{quantity}}개 = {{total_price}} 원</td>
				</tr>
				{{order_form.as_table}}
			</table>
		</div>
		<div id="order_detail_submit">
			<input class="submit" type="submit" value="입력"/>
		</div>
</form>
</div>


{% endblock %}